language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: HPfaR4bjak91KjP3OvEjsIOeb5UeFWcSYkqA76sIr3HOE9Kp5MppgR59+HFwgWafATS7p+0A8d6NFOSgoyJsbAh4vbdsX1laDl2DYP5STQZAlLxK6pYFgT2XHPO6ydpDqNDnlZ+Us1NrC1dwXywEHBmcMzwwQ4gxJw7R5JDaZPFlDHilC9SYNsgakMZvzqCeQ9WcPqMqJOMOXAa7hyakA92LCb0SEfg0Vn31L7TR5Ux6ozrI5hKy9mIIYq8nkxjjHTRGcGenOmDuPOpjV0o3egFI8/hnPXUeteajpsfjRpyzF+/0KuwflP++d7chC6ow4u5mCMXY93LE6kdPazdOLxg93ZJkak1+Kb4GWPe0cT+J6JE85NEQ2WbODDLSwLDG0TQyKr80T7gVQ809v+PqkIgtPn2gCb29kZdM0SwgyxqD95ZEJQ5OSu7suNHsNYBxTdOgZC5BGHkD3HDy5GnxuAYDE14K+InLoKGRsHDg8mlBdPZjJONbrDH0QCZZalMZcw8/fdY0iqNrnMdFE0bBG1BFXLQufugRABBRqCpmaiiAX3gY2GlxI8feKH+Uhcawgteo6Kv5aDDYBXU/KSD/vgAOqnZ8Z8NiOFylDQCBJBrSgtyCSEX5tfgxNW2ZeLQv6sYq2hhSfLR9NQ3i/jOyiLtKKwB1vsn4jYUGk7qZ0Vk=
